# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot = {
    loader.grub.enable = true;
    loader.grub.version = 2;
    loader.grub.device = "/dev/sda";
    initrd.availableKernelModules = [ "xhci_hcd" "ehci_pci" "ahci" "usb_storage" ];
    kernelModules = [ "kvm-intel" ];
    blacklistedKernelModules = [ "i915" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b1bbe328-e33e-4b24-93eb-61db847fde04";
      fsType = "ext4";
      options = "defaults,discard,noatime";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/c477113c-2b11-4000-b2a7-ec03b9d6f184";
      fsType = "ext4";
    };

  fileSystems."/mnt/datos" =
    { device = "/dev/disk/by-uuid/9331d983-0be1-4158-bf68-3272844f1c04";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0ebf51de-dd60-4ab7-9878-e681224e10e3"; }
    ];

  nix.maxJobs = 4;
  hardware.pulseaudio.enable = true;
}
