# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];


  # Use the GRUB 2 boot loader.
  boot = {
    loader.grub.enable = true;
    loader.grub.version = 2;
    loader.grub.device = "/dev/sda";
    initrd.availableKernelModules = [ "xhci_hcd" "ehci_pci" "ahci" "usb_storage" ];
    kernelModules = [ "tp_smapi" "thinkpad_acpi" "coretemp" "kvm-intel" ];
    initrd.kernelModules = [ "fbcon" "i915" ];
    extraModulePackages = [ config.boot.kernelPackages.tp_smapi ];
  };

  fileSystems."/" =
    { device = "/dev/sda3";
      fsType = "ext4";
      options = "defaults,noatime,discard";
    };

  swapDevices =
    [ { device = "/dev/sda4"; }
    ];

  nix.maxJobs = 4;
}
